// flow-typed signature: 026c430eeaf7f9cb41b3017433f0ec44
// flow-typed version: <<STUB>>/gsap-react-plugin_v^1.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gsap-react-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gsap-react-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gsap-react-plugin/gsap-react-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gsap-react-plugin/gsap-react-plugin.js' {
  declare module.exports: $Exports<'gsap-react-plugin/gsap-react-plugin'>;
}
