// flow-typed signature: 2141864aeca00aa767e72ec54843b1aa
// flow-typed version: <<STUB>>/lerp_v^1.0.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lerp/index' {
  declare module.exports: $Exports<'lerp'>;
}
declare module 'lerp/index.js' {
  declare module.exports: $Exports<'lerp'>;
}
