// flow-typed signature: 15c052d09e9b91b91b0a0d7bab702c06
// flow-typed version: <<STUB>>/pixi_v^0.3.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixi/core/globals' {
  declare module.exports: any;
}

declare module 'pixi/display/blendModes' {
  declare module.exports: any;
}

declare module 'pixi/display/DisplayObject' {
  declare module.exports: any;
}

declare module 'pixi/display/DisplayObjectContainer' {
  declare module.exports: any;
}

declare module 'pixi/display/MovieClip' {
  declare module.exports: any;
}

declare module 'pixi/display/Sprite' {
  declare module.exports: any;
}

declare module 'pixi/display/Stage' {
  declare module.exports: any;
}

declare module 'pixi/events/EventTarget' {
  declare module.exports: any;
}

declare module 'pixi/extras/CustomRenderable' {
  declare module.exports: any;
}

declare module 'pixi/extras/Rope' {
  declare module.exports: any;
}

declare module 'pixi/extras/Spine' {
  declare module.exports: any;
}

declare module 'pixi/extras/Strip' {
  declare module.exports: any;
}

declare module 'pixi/extras/TilingSprite' {
  declare module.exports: any;
}

declare module 'pixi/filters/AbstractFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/BlurFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/BlurXFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/BlurYFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/ColorMatrixFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/ColorStepFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/CrossHatchFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/DisplacementFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/DotScreenFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/FilterBlock' {
  declare module.exports: any;
}

declare module 'pixi/filters/GrayFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/InvertFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/PixelateFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/RGBSplitFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/SepiaFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/SmartBlurFilter' {
  declare module.exports: any;
}

declare module 'pixi/filters/TwistFilter' {
  declare module.exports: any;
}

declare module 'pixi/geom/Circle' {
  declare module.exports: any;
}

declare module 'pixi/geom/Ellipse' {
  declare module.exports: any;
}

declare module 'pixi/geom/matrix' {
  declare module.exports: any;
}

declare module 'pixi/geom/Point' {
  declare module.exports: any;
}

declare module 'pixi/geom/Polygon' {
  declare module.exports: any;
}

declare module 'pixi/geom/Rectangle' {
  declare module.exports: any;
}

declare module 'pixi/InteractionManager' {
  declare module.exports: any;
}

declare module 'pixi/loaders/AssetLoader' {
  declare module.exports: any;
}

declare module 'pixi/loaders/AtlasLoader' {
  declare module.exports: any;
}

declare module 'pixi/loaders/BitmapFontLoader' {
  declare module.exports: any;
}

declare module 'pixi/loaders/ImageLoader' {
  declare module.exports: any;
}

declare module 'pixi/loaders/JsonLoader' {
  declare module.exports: any;
}

declare module 'pixi/loaders/SpineLoader' {
  declare module.exports: any;
}

declare module 'pixi/loaders/SpriteSheetLoader' {
  declare module.exports: any;
}

declare module 'pixi/platform' {
  declare module.exports: any;
}

declare module 'pixi/primitives/Graphics' {
  declare module.exports: any;
}

declare module 'pixi/renderers/canvas/CanvasRenderer' {
  declare module.exports: any;
}

declare module 'pixi/renderers/canvas/graphics' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/compile' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/graphics' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/PixiShader' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/PrimitiveShader' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/shaders' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/StripShader' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/WebGLBatch' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/WebGLFilterManager' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/WebGLRenderer' {
  declare module.exports: any;
}

declare module 'pixi/renderers/webgl/WebGLRenderGroup' {
  declare module.exports: any;
}

declare module 'pixi/text/BitmapText' {
  declare module.exports: any;
}

declare module 'pixi/text/Text' {
  declare module.exports: any;
}

declare module 'pixi/textures/BaseTexture' {
  declare module.exports: any;
}

declare module 'pixi/textures/RenderTexture' {
  declare module.exports: any;
}

declare module 'pixi/textures/Texture' {
  declare module.exports: any;
}

declare module 'pixi/utils/autoDetectRenderer' {
  declare module.exports: any;
}

declare module 'pixi/utils/color' {
  declare module.exports: any;
}

declare module 'pixi/utils/debug' {
  declare module.exports: any;
}

declare module 'pixi/utils/Polyk' {
  declare module.exports: any;
}

declare module 'pixi/utils/raf' {
  declare module.exports: any;
}

declare module 'pixi/utils/spine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixi/core/globals.js' {
  declare module.exports: $Exports<'pixi/core/globals'>;
}
declare module 'pixi/display/blendModes.js' {
  declare module.exports: $Exports<'pixi/display/blendModes'>;
}
declare module 'pixi/display/DisplayObject.js' {
  declare module.exports: $Exports<'pixi/display/DisplayObject'>;
}
declare module 'pixi/display/DisplayObjectContainer.js' {
  declare module.exports: $Exports<'pixi/display/DisplayObjectContainer'>;
}
declare module 'pixi/display/MovieClip.js' {
  declare module.exports: $Exports<'pixi/display/MovieClip'>;
}
declare module 'pixi/display/Sprite.js' {
  declare module.exports: $Exports<'pixi/display/Sprite'>;
}
declare module 'pixi/display/Stage.js' {
  declare module.exports: $Exports<'pixi/display/Stage'>;
}
declare module 'pixi/events/EventTarget.js' {
  declare module.exports: $Exports<'pixi/events/EventTarget'>;
}
declare module 'pixi/extras/CustomRenderable.js' {
  declare module.exports: $Exports<'pixi/extras/CustomRenderable'>;
}
declare module 'pixi/extras/Rope.js' {
  declare module.exports: $Exports<'pixi/extras/Rope'>;
}
declare module 'pixi/extras/Spine.js' {
  declare module.exports: $Exports<'pixi/extras/Spine'>;
}
declare module 'pixi/extras/Strip.js' {
  declare module.exports: $Exports<'pixi/extras/Strip'>;
}
declare module 'pixi/extras/TilingSprite.js' {
  declare module.exports: $Exports<'pixi/extras/TilingSprite'>;
}
declare module 'pixi/filters/AbstractFilter.js' {
  declare module.exports: $Exports<'pixi/filters/AbstractFilter'>;
}
declare module 'pixi/filters/BlurFilter.js' {
  declare module.exports: $Exports<'pixi/filters/BlurFilter'>;
}
declare module 'pixi/filters/BlurXFilter.js' {
  declare module.exports: $Exports<'pixi/filters/BlurXFilter'>;
}
declare module 'pixi/filters/BlurYFilter.js' {
  declare module.exports: $Exports<'pixi/filters/BlurYFilter'>;
}
declare module 'pixi/filters/ColorMatrixFilter.js' {
  declare module.exports: $Exports<'pixi/filters/ColorMatrixFilter'>;
}
declare module 'pixi/filters/ColorStepFilter.js' {
  declare module.exports: $Exports<'pixi/filters/ColorStepFilter'>;
}
declare module 'pixi/filters/CrossHatchFilter.js' {
  declare module.exports: $Exports<'pixi/filters/CrossHatchFilter'>;
}
declare module 'pixi/filters/DisplacementFilter.js' {
  declare module.exports: $Exports<'pixi/filters/DisplacementFilter'>;
}
declare module 'pixi/filters/DotScreenFilter.js' {
  declare module.exports: $Exports<'pixi/filters/DotScreenFilter'>;
}
declare module 'pixi/filters/FilterBlock.js' {
  declare module.exports: $Exports<'pixi/filters/FilterBlock'>;
}
declare module 'pixi/filters/GrayFilter.js' {
  declare module.exports: $Exports<'pixi/filters/GrayFilter'>;
}
declare module 'pixi/filters/InvertFilter.js' {
  declare module.exports: $Exports<'pixi/filters/InvertFilter'>;
}
declare module 'pixi/filters/PixelateFilter.js' {
  declare module.exports: $Exports<'pixi/filters/PixelateFilter'>;
}
declare module 'pixi/filters/RGBSplitFilter.js' {
  declare module.exports: $Exports<'pixi/filters/RGBSplitFilter'>;
}
declare module 'pixi/filters/SepiaFilter.js' {
  declare module.exports: $Exports<'pixi/filters/SepiaFilter'>;
}
declare module 'pixi/filters/SmartBlurFilter.js' {
  declare module.exports: $Exports<'pixi/filters/SmartBlurFilter'>;
}
declare module 'pixi/filters/TwistFilter.js' {
  declare module.exports: $Exports<'pixi/filters/TwistFilter'>;
}
declare module 'pixi/geom/Circle.js' {
  declare module.exports: $Exports<'pixi/geom/Circle'>;
}
declare module 'pixi/geom/Ellipse.js' {
  declare module.exports: $Exports<'pixi/geom/Ellipse'>;
}
declare module 'pixi/geom/matrix.js' {
  declare module.exports: $Exports<'pixi/geom/matrix'>;
}
declare module 'pixi/geom/Point.js' {
  declare module.exports: $Exports<'pixi/geom/Point'>;
}
declare module 'pixi/geom/Polygon.js' {
  declare module.exports: $Exports<'pixi/geom/Polygon'>;
}
declare module 'pixi/geom/Rectangle.js' {
  declare module.exports: $Exports<'pixi/geom/Rectangle'>;
}
declare module 'pixi/index' {
  declare module.exports: $Exports<'pixi'>;
}
declare module 'pixi/index.js' {
  declare module.exports: $Exports<'pixi'>;
}
declare module 'pixi/InteractionManager.js' {
  declare module.exports: $Exports<'pixi/InteractionManager'>;
}
declare module 'pixi/loaders/AssetLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/AssetLoader'>;
}
declare module 'pixi/loaders/AtlasLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/AtlasLoader'>;
}
declare module 'pixi/loaders/BitmapFontLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/BitmapFontLoader'>;
}
declare module 'pixi/loaders/ImageLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/ImageLoader'>;
}
declare module 'pixi/loaders/JsonLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/JsonLoader'>;
}
declare module 'pixi/loaders/SpineLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/SpineLoader'>;
}
declare module 'pixi/loaders/SpriteSheetLoader.js' {
  declare module.exports: $Exports<'pixi/loaders/SpriteSheetLoader'>;
}
declare module 'pixi/platform.js' {
  declare module.exports: $Exports<'pixi/platform'>;
}
declare module 'pixi/primitives/Graphics.js' {
  declare module.exports: $Exports<'pixi/primitives/Graphics'>;
}
declare module 'pixi/renderers/canvas/CanvasRenderer.js' {
  declare module.exports: $Exports<'pixi/renderers/canvas/CanvasRenderer'>;
}
declare module 'pixi/renderers/canvas/graphics.js' {
  declare module.exports: $Exports<'pixi/renderers/canvas/graphics'>;
}
declare module 'pixi/renderers/webgl/compile.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/compile'>;
}
declare module 'pixi/renderers/webgl/graphics.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/graphics'>;
}
declare module 'pixi/renderers/webgl/PixiShader.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/PixiShader'>;
}
declare module 'pixi/renderers/webgl/PrimitiveShader.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/PrimitiveShader'>;
}
declare module 'pixi/renderers/webgl/shaders.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/shaders'>;
}
declare module 'pixi/renderers/webgl/StripShader.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/StripShader'>;
}
declare module 'pixi/renderers/webgl/WebGLBatch.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/WebGLBatch'>;
}
declare module 'pixi/renderers/webgl/WebGLFilterManager.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/WebGLFilterManager'>;
}
declare module 'pixi/renderers/webgl/WebGLRenderer.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/WebGLRenderer'>;
}
declare module 'pixi/renderers/webgl/WebGLRenderGroup.js' {
  declare module.exports: $Exports<'pixi/renderers/webgl/WebGLRenderGroup'>;
}
declare module 'pixi/text/BitmapText.js' {
  declare module.exports: $Exports<'pixi/text/BitmapText'>;
}
declare module 'pixi/text/Text.js' {
  declare module.exports: $Exports<'pixi/text/Text'>;
}
declare module 'pixi/textures/BaseTexture.js' {
  declare module.exports: $Exports<'pixi/textures/BaseTexture'>;
}
declare module 'pixi/textures/RenderTexture.js' {
  declare module.exports: $Exports<'pixi/textures/RenderTexture'>;
}
declare module 'pixi/textures/Texture.js' {
  declare module.exports: $Exports<'pixi/textures/Texture'>;
}
declare module 'pixi/utils/autoDetectRenderer.js' {
  declare module.exports: $Exports<'pixi/utils/autoDetectRenderer'>;
}
declare module 'pixi/utils/color.js' {
  declare module.exports: $Exports<'pixi/utils/color'>;
}
declare module 'pixi/utils/debug.js' {
  declare module.exports: $Exports<'pixi/utils/debug'>;
}
declare module 'pixi/utils/Polyk.js' {
  declare module.exports: $Exports<'pixi/utils/Polyk'>;
}
declare module 'pixi/utils/raf.js' {
  declare module.exports: $Exports<'pixi/utils/raf'>;
}
declare module 'pixi/utils/spine.js' {
  declare module.exports: $Exports<'pixi/utils/spine'>;
}
